### ISSUE TITLE
multiple tabs not separated

### ISSUE THREAD

**Issue by trebitzki** [k08045kk/CopyTabTitleUrl#44] opened 2021-12-07 15:50 UTC
I enabled "Separate multiple tabs with a newline character", but the tabs are not separated.
Using version 2.2.0

**Comment by k08045kk** [comment] 2021-12-08 00:06
Thank you for pointing this out.
However, I have not been able to reproduce the problem.
I'm sorry, but could you please provide more detailed information?


What is your operating system?
What is your browser and its version?
What is your version of the extension? (v2.2.0)
Can you show the reproduction pattern?
What is the settings when you reproduce it? (What have you changed from the default settings?)
What is the display of the tabs when you reproduce it? (What is the URL?)
What is the format when you reappeared? (title, url, title and url, format)
What is the action when you reproduce it? (context menu, browser action, shortcut)
What is the target when you reproduce it? (tab, selected tabs, window, all)
What is the result when you reproduce it?
What is the expected result when you reproduce it?
Does the problem always occur? Occasionally?


Separate multiple tabs with a newline character" is an option that assumes the following behavior.
The following is an example of how it works: 
1. Display three tabs of "https://www.google.com/" in a window.
2. target "window" from browser action and copy the title.
  + Turn on "Separate multiple tabs with a newline character

	Google
	Google
	Google.

+ Turn off "Separate multiple tabs with a newline character

	Google Google Google


You may be able to work around the problem with the formatting feature. Try ${enter} / ${CR} / ${LF}.


When using the "Extended Mode" function, be sure to turn on "Extended Mode". If it is turned off, the default settings will be used. Settings that are not displayed on the setting screen will use the default settings.


That's all.

**Comment by trebitzki** [comment] 2021-12-19 18:02
Hi toshi,

Thanks for getting back to me.

I’m using Catalina here on my Macbook Air, mid 2012.

Your questions:

OS: macOS Catalina 10.15.7
Browser: Firefox 95.0.2 64-bit
Extension: 2.2.0

Settings: Default

Pattern I want:
Title1
URL1

Title2
URL2

etc.

What I’m getting (always):
Title1
URL1
Title2
URL2
etc.

I don’t see "Separate multiple tabs with a newline character” in the 2.2.0 settings.

It seems strange not to separate the tab infos with an empty line. How can I get the tab infos separated from each other?

Thanks for your help!
Timm

I’ll try your solution on my other Mac with El Capitan when you reply.

**Comment by k08045kk** [comment] 2021-12-20 06:17
Thank you for your answer.

As far as your answer is concerned, the results you are getting are working as per the specification. The extension is working as intended. There are no specification changes in this case.


> I don't see "Separate multiple tabs with a newline character" in the 2.2.0 settings.

→ Enable `Extended mode`.


> How can I get the tab infos separated from each other?

→ I believe that using the [Format] function will solve the problem.
+ When `Separate multiple tabs with a newline character` is enabled.
  + `${title}${enter}${url}${enter}`.
+ When `Separate multiple tabs with a newline character` is disabled
  + `${title}${enter}${url}${enter}${enter}`.

※ If you need to change the newline character, you can also use `${CR} / ${LF}`.


That's all.

**Comment by k08045kk** [comment] 2022-03-04 13:52
[Separate multiple tabs with a newline character] was changed to [Separate multiple tabs] in v2.3.0. You can freely change the separator character that separates multiple tabs.

You can use the following settings to separate multiple tabs with a blank line. Please try it.

```
Separate multiple tabs: ${enter}${enter}
```

**Comment by k08045kk** [comment] 2022-09-10 07:00
I will close this issue. Please comment if you have any questions.

**Closed by k08045kk** 2022-09-10 07:00 UTC
Labels: question, scheduled to be closed
